### ISSUE TITLE
App Crash iOS

### ISSUE THREAD

**Issue by DrBlackBird** [graphefruit/Beanconqueror#553]
Hi!

I downloaded the app yesterday and wanted to start to track my data but and non of my devices the App starts. It’s just shows the splash screen and immediately crashes. 

Devices used:

iPad Pro 12.1 iOS 15.5
iPhone 11 iOS 16.5

any ideas?

thanks a lot!

**Comment by graphefruit** [comment]
Hey @DrBlackBird,
Very sorry to hear this.
A user Yesterday reported on Reddit the same, but it was fixed after updating his os.
On my iPhone 8 with iOS 16.4.1 it works fine even with a clean installation.
I'll go and update it to the latest os and have a look.
Also I'll go and try this evening downloading a emulator with the same os specification you reported here.

A uninstall, rebooting the device and reinstalling the app didn't help I think?

**Comment by DrBlackBird** [comment]
> Hey @DrBlackBird,
> 
> Very sorry to hear this.
> 
> A user Yesterday reported on Reddit the same, but it was fixed after updating his os.
> 
> On my iPhone 8 with iOS 16.4.1 it works fine even with a clean installation.
> 
> I'll go and update it to the latest os and have a look.
> 
> Also I'll go and try this evening downloading a emulator with the same os specification you reported here.
> 
> 
> 
> A uninstall, rebooting the device and reinstalling the app didn't help I think?
> 
> 
> 
> Greetings
> 
> Lars

OMG! Lars, I am so sorry. iPad was on 15.5 and iPhone on 16.1.1. iPad works now after the update to 16.5 I assume the same will be the case for the iPhone. I will report later. But it's strange that later versions are not working properly, right?

Best and thanks for your help!

**Comment by Cathfaern** [comment]
Hi, I have the same problem, it started today after the new update, it was working yesterday. I have an iPhone 7, I’ve done an update to the latest available (15.7.6), but the crash persists.

**Comment by graphefruit** [comment]
@Cathfaern i'll have a look this evening. 
I've published 6.4.1 one correlation needs to lead sadly into this issue

**Comment by lksnmnn** [comment]
Came to report this crash too. (iPhone 6 on latest 15.7.6 or so).
Let me know if you need the crash report.

**Comment by graphefruit** [comment]
Yes please mail me: info@beanconqueror.com

Thanks

**Comment by DrBlackBird** [comment]
@graphefruit after the Update to 16.5 it's also working on the phone. Very strange! Thanks for your help anyways!

**Comment by graphefruit** [comment]
Issue is tackeld down for every phones which cant update to 16.5, hopefully I can push this evening the new version. thanks for your patience

**Comment by graphefruit** [comment]
App was submitted to apple, now thumbs being pressed for a fast release.

**Comment by lksnmnn** [comment]
Reminds me of the good old days of https://appreviewtimes.com/

**Comment by graphefruit** [comment]
New release is out! Please update, the app should start normally now :)
Else please do a new issue.
Thanks for your patience
Lars
